### ISSUE TITLE
functionality on browser not working and demo.html example doesn't run

### ISSUE THREAD

**Issue by Anthonyzou** [camertron/cldr-segmentation.js#15] opened 2020-12-10 22:01 UTC
Hi I tried running the demo.html and didn't get it running. Everything seems to get loaded but it errors out.

I think usage on the browser for utfstring should be `UtfString.stringToCodePoints` instead of `utfString.stringToCodePoints`.

![Screen Shot 2020-12-10 at 2 58 07 PM](https://user-images.githubusercontent.com/1567160/101834857-1e532d00-3af8-11eb-9a36-67283d326af7.png)
![Screen Shot 2020-12-10 at 2 58 25 PM](https://user-images.githubusercontent.com/1567160/101834891-2ad78580-3af8-11eb-92a6-bd1b56fa4ea9.png)

**Comment by camertron** [comment] 2020-12-14 18:08
Hey @Anthonyzou, thanks for filing an issue. This `utfstring` require has been the cause of so many issues...

It looks like grunt transforms `require('utfstring')` into `window.utfstring`, which should be `window.UtfString`. It works in a node environment because `require` grabs that object directly and doesn't need to pull it off `window`. Ugh, what a pain.

Fixed as of v2.1.2

**Closed as completed by camertron** 2020-12-14 18:08 UTC

**Comment by Anthonyzou** [comment] 2020-12-14 18:27
Thanks a lot. Maybe it would make sense to use a nicer bundler like [Parcel js](https://parceljs.org/)?

**Comment by camertron** [comment] 2020-12-14 18:30
@Anthonyzou maybe it would! I'm just not a js guy really and don't relish learning yet another packaging system. If you've got some spare time, would you be interested in submitting a PR?

**Comment by Anthonyzou** [comment] 2020-12-14 18:43
Yeah I could look into it. I can't make any guarantees because the build setup is pretty unique.

**Comment by camertron** [comment] 2020-12-14 18:54
Thanks! I'm curious, what's unique about the build setup?

**Comment by Anthonyzou** [comment] 2020-12-14 19:12
It's kind of hard to determine a single entrypoint and I probably wouldn't want to move the files around because there seems to be Ruby files that reads/edits the source files.

**Comment by camertron** [comment] 2020-12-15 19:52
The ruby code is responsible for generating the state tables and suppression lists. It doesn't read or edit the files, it just writes them out. I'm happy to make any Ruby changes based on your Javascript changes when you're ready to merge.

There's no single entry point because it's a library you'd import and use the objects from. Is there a better way to do things?

**Comment by SStauden** [comment] 2020-12-21 01:40
Hey,I use the updated library (v2.1.2) in an Angular 10 project and receive the same error 

`TypeError: Cannot read property 'stringToCodePoints' of undefined` 

on the browser, when importing the lib with `import * as cldrSegmentation from 'cldr-segmentation';`.
Any idea?

**Comment by camertron** [comment] 2020-12-21 03:47
@SStauden  hmm. Do you have an example app or code snippet that can reproduce the error you can share with me?

**Comment by camertron** [comment] 2021-01-05 18:34
@SStauden I think your issue should be fixed with the v2.1.3 release. Can you give it a try and let me know?

**Comment by SStauden** [comment] 2021-02-08 13:12
Yes, the update resolved this issue. Thanks!
