### ISSUE TITLE
Suppressions prevent sentence split when suppressed text appears in a word

### ISSUE THREAD

**Issue by vschaeidt** [camertron/cldr-segmentation.js#10] opened 2020-05-11 10:48 UTC
When a suppression exception appears randomly in a word that ends a sentence (and has thus a point following it), the sentence does not break.

The failing test to reproduce that behavior for english would be:

```
it('splits correctly using uli exceptions when they appear in a word ending a sentence', () => {
      let str = "Hi, my name is Philipp. Just because I can.";
      let result = cldrSegmentation.sentenceSplit(str, englishSuppressions);

      expect(result).toEqual(["Hi, my name is Philipp. ", "Just because I can."]);
    });
```

Or for german:

```
it('splits correctly using uli exceptions when they appear in a german word ending a sentence', () => {
      let str = "Dies ist ein test Satz. Und hier ein Zweiter.";
      const germanSuppressions = cldrSegmentation.suppressions.de;
      let result = cldrSegmentation.sentenceSplit(str, germanSuppressions);

      expect(result).toEqual(["Dies ist ein test Satz. ", "Und hier ein Zweiter."]);
    });
```

Is that behavior intended, or should it rather split the sentence, when the suppression exception is not standing alone (with a space preceding)?

**Comment by camertron** [comment] 2020-05-11 17:25
Hey @vschaeidt, that looks like a bug! I was able to reproduce, and this definitely isn't the right behavior. If you add more than one space between the two sentences, it works as expected. A single space _should_ be enough for a break however. I'll look into fixing it.

**Comment by camertron** [comment] 2020-05-23 04:40
Hey @vschaeidt, this should be fixed in v2.0.2. Turns out the problem actually happens because "pp." is an English suppression, and "z." is a German one. ICU4J, which this library is based on, also does this incorrectly.

**Closed as completed by camertron** 2020-05-23 04:40 UTC

**Comment by vschaeidt** [comment] 2020-05-25 06:18
Thanks a lot for the fast update, but with the changes from 2.0.2 I get:

`Cannot find module 'UtfString' from '../../node_modules/cldr-segmentation/dist/cldr-segmentation.js'`

Was the renaming intentional? Because utfstring does not seem to reflect this change.

**Comment by camertron** [comment] 2020-05-26 17:15
Hmm very curious.

Not sure what renaming are you referring to tho, @vschaeidt? I changed an unrelated part of the code.

**Comment by camertron** [comment] 2020-05-26 17:29
@vschaeidt I just tried adding cldr-segmentation to a test project and it works as expected:

```javascript
var cldrSeg = require('cldr-segmentation');
cldrSeg.sentenceSplit("My name is Philipp. Just because I can.", cldrSeg.suppressions.en);
```

**Comment by camertron** [comment] 2020-05-26 17:46
Shoot, ok I see the renaming you're talking about. I don't know/remember how that happened, definitely not intentional. Mac OS's case-insensitive filesystem strikes again, which is why it worked on my machine. Was able to reproduce the `UtfString` issue in a Docker container.

Just published v2.0.3. Apologies for the confusion :)

**Comment by vschaeidt** [comment] 2020-05-27 05:56
Thanks for the fast fix, maybe I was a little too unspecific with my question ;)

**Comment by vschaeidt** [comment] 2020-05-28 07:58
Sorry to bother you again, but it seems, that v2.0.3 has not been published yet ;)

**Comment by camertron** [comment] 2020-05-28 17:30
@vschaeidt oops sorry about that! Should be published now :)
